<a href="https://colab.research.google.com/github/pragya2003sah/deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


# INTRODUCING TENSORS


In [ ]:
# scalar
scalar=torch.tensor(7) # creating a scalar tensor
scalar.item() #extracting the tensor to python int

7

In [ ]:
# vector
vector=torch.tensor([8,8])
vector.shape

torch.Size([2])

In [ ]:
MATRIX=torch.tensor([[7,8],[9,0]])
MATRIX[1]

tensor([9, 0])

In [ ]:
MATRIX.ndim

2

tensor.torch(7) converts a element of tensor data type, similar to numpys ndarray but with added capabilities of GPU.

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [2,3,4],
                      [3,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [ ]:
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [ ]:
TENSOR[0,1]

tensor([2, 3, 4])

# RANDOM TENSORS
random tensors are important as the way any neural network learns is that they start with random numbers and then adjust those random numbers to better fit the data.

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5157, 0.7063, 0.9098, 0.4651],
        [0.6982, 0.9360, 0.5231, 0.5836],
        [0.2775, 0.0256, 0.7934, 0.9295]])

In [ ]:
random_image_tensor=torch.rand(size=(3,2,3))
random_image_tensor.ndim
random_image_tensor.shape
random_image_tensor

tensor([[[0.9651, 0.0319, 0.4111],
         [0.1140, 0.3476, 0.3621]],

        [[0.5484, 0.7484, 0.2229],
         [0.8261, 0.2263, 0.6055]],

        [[0.1047, 0.4820, 0.9035],
         [0.8338, 0.7625, 0.9151]]])

# ZEROES AND ONES

In [ ]:
# creating tensor with all zeroes
zeroes=torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# all ones
ones=torch.ones(size=(1,2))
ones

tensor([[1., 1.]])

# creating a range of tensors and tensors-like

In [ ]:
torch.arange(start=0,end=30,step=5)

tensor([ 0,  5, 10, 15, 20, 25])

In [ ]:
 # tensor-like- when we want to create a new tensor with the shape of another tensor without explicitly telling the shape
like_tensors=torch.zeros_like(input=zeroes)
like_tensors

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# TENSOR DATATYPES

float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor.dtype


torch.float32

In [ ]:
float_16_tensor=torch.tensor([2,3,4],
                             dtype=torch.float16,
                             device=None,
                             requires_grad=False)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 6., 18., 36.])

In [ ]:
# tensor attributes
print(float_32_tensor.dtype)
print(float_32_tensor.shape)
print(float_32_tensor.device)

torch.float32
torch.Size([3])
cpu


# manipulating Tensors
operations include-
1-addition
2-subtraction
3-multiplication(element-wise)
4-division
5-matrix multiplication
these operations are helpful to convert our random tensors to be more similar to data

In [ ]:
tensor=torch.tensor([1,2,3])

In [ ]:
#addition
tensor+10

tensor([11, 12, 13])

In [ ]:
#muliplication
tensor*10

tensor([10, 20, 30])

In [ ]:
#subtaction
tensor-1

tensor([0, 1, 2])

In [ ]:
# inbuilt function
torch.mul(tensor,10)
torch.add(tensor,10)
torch.sub(tensor,1)

tensor([0, 1, 2])

In [ ]:
# matrix multiplication
print(tensor*tensor)
print(torch.matmul(tensor,tensor))
#matmul gives us a dot product of the matrix multiplication

tensor([1, 4, 9])
tensor(14)


# rules for matrix multiplcation
1> inner dimension must match((3,2)@(3,2) - no (3,2)@(2,3)-yes
                              )
2>the resulting matrix has a shape of outer dimentions

In [ ]:
# shape errors and how to deal with them
tensor_A=torch.tensor([[1,2],
                       [2,3],
                       [3,4]])
tensor_B=torch.tensor([[2,5],
                       [3,6],
                       [5,7]])
torch.mm(tensor_A,tensor_B) # mm is a shortform of matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# transposing to fix the issue so that the inner dimensions of both matrices remain same.
tensor_B.T,tensor_B.T.shape


(tensor([[2, 3, 5],
         [5, 6, 7]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[12, 15, 19],
        [19, 24, 31],
        [26, 33, 43]])

In [ ]:
# tensor aggregation
x=torch.arange(1,90,10)
x,x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81]), torch.int64)

In [ ]:
torch.min(x),x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x),x.max()

(tensor(81), tensor(81))

In [ ]:
torch.mean(x) # eg of worong datatype error

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(41.)

In [ ]:
torch.sum(x)

tensor(369)

In [ ]:
# positional min and max- finding the position of the min and max element
min=torch.argmin(x) # returns the index
min,x[0]

(tensor(0), tensor(1))

In [ ]:
max=torch.argmax(x)
max

tensor(8)

In [ ]:
x[8]

tensor(81)

# reshaping,stacking , squeezing and unsqueeing techniques
* Reshaping=reshapes the shape of the tensor to a defined Shape Type
* view= shares the same memory location as input tensor and if i change the view the original also changes. functions very similar to reshape only difference being the memory.
* stacking- combines multiple tensors on top of each other(vstack) or side by side(hstack)
* squeeze- removes all `1` dimensions from a tensor
* unsqueeze- add a `1` dimension to a target tensor
* permute-return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=torch.reshape(x,(9,1))
x_reshaped,x_reshaped.shape
# the new dimension must be compatible with the original shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped=torch.reshape(x,(3,3))
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
z=x.view(1,9)
z


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
z=x.view(3,3)
z,x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
z[0,2]=5
z,x
# z and x both share the same memory location although the dimension hasnt changed, the values accouding to the dimension changed(eg-z[0] represents the whole 0 vector whereas x[0] just represts a scalar,but by changing z we changed multiple scalars from x too)

(tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 5., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked_0=torch.stack([x,x],dim=0) #side by side
x_stacked_1=torch.stack([x,x],dim=1) #column by column
x_stacked_0,x_stacked_1


(tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.],
         [1., 2., 5., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1., 1.],
         [2., 2.],
         [5., 5.],
         [4., 4.],
         [5., 5.],
         [6., 6.],
         [7., 7.],
         [8., 8.],
         [9., 9.]]))

In [ ]:
torch.squeeze(x_stacked_0),x_stacked_0

(tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.],
         [1., 2., 5., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1., 2., 5., 4., 5., 6., 7., 8., 9.],
         [1., 2., 5., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
torch.squeeze(x_reshaped),x_reshaped

(tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[1., 2., 5.],
         [4., 5., 6.],
         [7., 8., 9.]]))

these squeeze functions did not work because there was no 1 dimension present in the tensor


In [ ]:
dum=torch.arange(1.,9.)
dum

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
dum=dum.reshape((1,8))

In [ ]:
dum.squeeze().shape

torch.Size([8])

In [ ]:
dum.unsqueeze(dim=1),dum.unsqueeze(dim=1).shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8.]]]), torch.Size([1, 1, 8]))

In [ ]:
dum.unsqueeze(dim=2),dum.unsqueeze(dim=1).shape

(tensor([[[1.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.]]]),
 torch.Size([1, 1, 8]))

In [ ]:
# permute- rearranges the dimensions by their in index-based
# it returns a view so changing the permutation changes the original
x_original=torch.rand(size=(35,35,3))
x_permuted=x_original.permute(2,0,1)# index 0->1 1->2 2->0
x_original.shape,x_permuted.shape
x_permuted[0,0,0]=3
x_original[0,0,0],x_permuted[0,0,0]
# although the dimension doesnt change the values changed

(tensor(3.), tensor(3.))

In [ ]:
#indexing
x=torch.arange(1,10).reshape(1,3,3)
print(x,x.shape)
print(x[0])
print(x[0,0])
print(x[0,0,0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [ ]:
# : to select all
x[:,1,2]

tensor([6])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

# pytorch and numpy
* convert numpy array to tensor- `torch.from_numpy(ndarray)`
* convert tensor to numpy - `torch.Tensor.numpy()`

In [ ]:
import numpy as np
array=np.arange(1.,8.)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensor=torch.from_numpy(array)
tensor
# default type of ndarray is float64. so the resultunt tensor will also be of float64.

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
array[1]=10
array,tensor

(array([ 1., 10.,  3.,  4.,  5.,  6.,  7.]),
 tensor([ 1., 10.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

In [ ]:
array=array+1
array,tensor

(array([ 2., 11.,  4.,  5.,  6.,  7.,  8.]),
 tensor([ 1., 10.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

In [ ]:
array[0]=9
array,tensor
# since array=array+1 is creating a new variable in a new space, noe changing array does not impact the tensor

(array([ 9., 11.,  4.,  5.,  6.,  7.,  8.]),
 tensor([ 1., 10.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

original array and tensor share the same memory that is why any inplace change to the array reflect in the tensor.

but array=array+1 creates a new array with a different location thus any change is not shown

In [ ]:
tensor=torch.ones(size=(3,3))
numpy_tensor=tensor.numpy()
numpy_tensor,tensor

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [ ]:
tensor[0,0]=0
tensor,numpy_tensor

(tensor([[0., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 array([[0., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

 numpy only works with cpu.

so if  a tensor on a gpu, if we do tensor.numpy(), it will result in an error.
we first have to convert the tensor to cpu using .cpu() and then convert to numpy

# reproducibility(trying to take random out of random)
getting the same random nos everytime.it is done to reduce the randomness.

* random seed- to get the same random no. irrespective of the machine or time it is generated

In [ ]:
import torch
RANDOM_TENSOR=42
torch.manual_seed(RANDOM_TENSOR)
random_A=torch.rand(3,4)
torch.manual_seed(RANDOM_TENSOR)
random_B=torch.rand(3,4)
print(random_A)
print(random_B)
print(random_A==random_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
torch.cuda.device_count()

0

In [ ]:
import torch

In [ ]:
a=torch.tensor([1,2])
b=torch.tensor([[1],
                [2],
                [3]])
a+b

tensor([[2, 3],
        [3, 4],
        [4, 5]])